"""Split flag_notes into blaty_note, cokoly_note, uwagi_note

Revision ID: 1946b83a2344
Revises: d0732d295bd8
Create Date: 2025-07-11 16:23:53.061007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1946b83a2344"
down_revision: Union[str, Sequence[str], None] = "d0732d295bd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("blaty_note", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("cokoly_note", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("uwagi_note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "uwagi_note")
    op.drop_column("projects", "cokoly_note")
    op.drop_column("projects", "blaty_note")
    # ### end Alembic commands ###
