"""initial schema

Revision ID: 73bcd758f17d
Revises:
Create Date: 2025-08-06 18:24:02.526015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73bcd758f17d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accessories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cabinet_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kitchen_type", sa.String(), nullable=False),
        sa.Column("nazwa", sa.String(), nullable=False),
        sa.Column("hdf_plecy", sa.Boolean(), nullable=False),
        sa.Column("listwa_count", sa.Integer(), nullable=False),
        sa.Column("listwa_w_mm", sa.Float(), nullable=True),
        sa.Column("listwa_h_mm", sa.Float(), nullable=True),
        sa.Column("wieniec_count", sa.Integer(), nullable=False),
        sa.Column("wieniec_w_mm", sa.Float(), nullable=True),
        sa.Column("wieniec_h_mm", sa.Float(), nullable=True),
        sa.Column("bok_count", sa.Integer(), nullable=False),
        sa.Column("bok_w_mm", sa.Float(), nullable=True),
        sa.Column("bok_h_mm", sa.Float(), nullable=True),
        sa.Column("front_count", sa.Integer(), nullable=False),
        sa.Column("front_w_mm", sa.Float(), nullable=True),
        sa.Column("front_h_mm", sa.Float(), nullable=True),
        sa.Column("polka_count", sa.Integer(), nullable=False),
        sa.Column("polka_w_mm", sa.Float(), nullable=True),
        sa.Column("polka_h_mm", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kitchen_type", sa.String(), nullable=False),
        sa.Column("order_number", sa.String(), nullable=False),
        sa.Column("client_name", sa.String(), nullable=True),
        sa.Column("client_address", sa.String(), nullable=True),
        sa.Column("client_phone", sa.String(), nullable=True),
        sa.Column("client_email", sa.String(), nullable=True),
        sa.Column("blaty", sa.Boolean(), nullable=False),
        sa.Column("blaty_note", sa.Text(), nullable=True),
        sa.Column("cokoly", sa.Boolean(), nullable=False),
        sa.Column("cokoly_note", sa.Text(), nullable=True),
        sa.Column("uwagi", sa.Boolean(), nullable=False),
        sa.Column("uwagi_note", sa.Text(), nullable=True),
        sa.Column("flag_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("value_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "project_cabinets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("body_color", sa.String(), nullable=False),
        sa.Column("front_color", sa.String(), nullable=False),
        sa.Column("handle_type", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("adhoc_width_mm", sa.Float(), nullable=True),
        sa.Column("adhoc_height_mm", sa.Float(), nullable=True),
        sa.Column("adhoc_depth_mm", sa.Float(), nullable=True),
        sa.Column("formula_offset_mm", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["type_id"], ["cabinet_types.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_cabinet_accessories",
        sa.Column("project_cabinet_id", sa.Integer(), nullable=False),
        sa.Column("accessory_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accessory_id"], ["accessories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_cabinet_id"], ["project_cabinets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_cabinet_id", "accessory_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_cabinet_accessories")
    op.drop_table("project_cabinets")
    op.drop_table("settings")
    op.drop_table("projects")
    op.drop_table("cabinet_types")
    op.drop_table("accessories")
    # ### end Alembic commands ###
