KITCHEN_TYPES = ["LOFT", "PARIS", "WINO"]

REPORT_MARGIN_MM_MIN = 0
REPORT_MARGIN_MM_MAX = 40
REPORT_LEFT_MARGIN_MM_DEFAULT = 5
REPORT_RIGHT_MARGIN_MM_DEFAULT = 5
REPORT_TOP_MARGIN_MM_DEFAULT = 4
REPORT_BOTTOM_MARGIN_MM_DEFAULT = 4

REPORT_NOTES_COLUMN_WIDTH_PERCENT_MIN = 15
REPORT_NOTES_COLUMN_WIDTH_PERCENT_MAX = 45
REPORT_NOTES_COLUMN_WIDTH_PERCENT_DEFAULT = 28

REPORT_COLUMN_GAP_MM_MIN = 0.0
REPORT_COLUMN_GAP_MM_MAX = 10.0
REPORT_COLUMN_GAP_MM_DEFAULT = 2.0

REPORT_ROW_SPACING_PT_MIN = 0
REPORT_ROW_SPACING_PT_MAX = 12
REPORT_ROW_SPACING_PT_DEFAULT = 2
