name: Build and Release EXE

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run PyInstaller build script
        shell: pwsh
        run: ./scripts/build.ps1

      - name: Create ZIP with version
        run: |
          $version = Get-Date -Format "yyyyMMdd-HHmmss"
          Compress-Archive -Path dist/cabplanner.exe -DestinationPath "cabplanner-$version.zip"
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cabplanner-${{ env.VERSION }}
          name: Cabplanner ${{ env.VERSION }}
          files: cabplanner-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
